# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BMI_Program(object):
    def setupUi(self, BMI_Program):
        BMI_Program.setObjectName("BMI_Program")
        BMI_Program.resize(883, 433)
        BMI_Program.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.label = QtWidgets.QLabel(BMI_Program)
        self.label.setGeometry(QtCore.QRect(20, 40, 131, 51))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"font: 20pt \"Sylfaen\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(BMI_Program)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 131, 51))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"font: 20pt \"Sylfaen\";")
        self.label_2.setObjectName("label_2")
        self.height_info = QtWidgets.QLineEdit(BMI_Program)
        self.height_info.setGeometry(QtCore.QRect(190, 50, 171, 41))
        self.height_info.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);")
        self.height_info.setObjectName("height_info")
        self.weight_info = QtWidgets.QLineEdit(BMI_Program)
        self.weight_info.setGeometry(QtCore.QRect(190, 120, 171, 41))
        self.weight_info.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);")
        self.weight_info.setObjectName("weight_info")
        self.calculate_button = QtWidgets.QPushButton(BMI_Program)
        self.calculate_button.setGeometry(QtCore.QRect(90, 190, 181, 51))
        self.calculate_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Sylfaen\";\n"
"border-color: rgb(255, 255, 255);")
        self.calculate_button.setObjectName("calculate_button")
        self.label_3 = QtWidgets.QLabel(BMI_Program)
        self.label_3.setGeometry(QtCore.QRect(540, 40, 251, 61))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"text-decoration: underline;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(255, 255, 255);\n"
"font: 20pt \"Sylfaen\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(BMI_Program)
        self.label_4.setGeometry(QtCore.QRect(450, 110, 81, 61))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"font: 14pt \"Sylfaen\";")
        self.label_4.setObjectName("label_4")
        self.result_section = QtWidgets.QTextBrowser(BMI_Program)
        self.result_section.setGeometry(QtCore.QRect(550, 100, 256, 192))
        self.result_section.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.result_section.setObjectName("result_section")

        self.retranslateUi(BMI_Program)
        QtCore.QMetaObject.connectSlotsByName(BMI_Program)

    def retranslateUi(self, BMI_Program):
        _translate = QtCore.QCoreApplication.translate
        BMI_Program.setWindowTitle(_translate("BMI_Program", "BMI Program"))
        self.label.setText(_translate("BMI_Program", "Height"))
        self.label_2.setText(_translate("BMI_Program", "Weight"))
        self.calculate_button.setText(_translate("BMI_Program", "Calculate"))
        self.label_3.setText(_translate("BMI_Program", "Result Section"))
        self.label_4.setText(_translate("BMI_Program", "Result: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BMI_Program = QtWidgets.QWidget()
    ui = Ui_BMI_Program()
    ui.setupUi(BMI_Program)
    BMI_Program.show()
    sys.exit(app.exec_())
